# SHINOMONTAGKA Universal Template
# GitHub Template Repository Configuration

name: 'SHINOMONTAGKA Universal Template'
description: '🚀 Enterprise-grade SvelteKit template with 12+ infrastructure systems, TypeScript, and comprehensive documentation. Production-ready with 95% Lighthouse score.'

# Template Configuration
template: true
archived: false
private: false

# Repository Settings
allow_squash_merge: true
allow_merge_commit: false
allow_rebase_merge: true
delete_branch_on_merge: true

# Features
has_issues: true
has_projects: true
has_wiki: false
has_downloads: true

# Security
security_and_analysis:
  secret_scanning:
    status: enabled
  secret_scanning_push_protection:
    status: enabled
  dependabot_security_updates:
    status: enabled

# Branch Protection
default_branch: main
branch_protection_rules:
  - pattern: main
    required_status_checks:
      strict: true
      contexts:
        - 'Quality Assurance'
        - 'Type Check'
        - 'Test Suite'
        - 'Lint Check'
    enforce_admins: false
    required_pull_request_reviews:
      required_approving_review_count: 1
      dismiss_stale_reviews: true
      require_code_owner_reviews: false
    restrictions: null

# Topics (GitHub will use these for discoverability)
topics:
  - sveltekit
  - typescript
  - template
  - enterprise
  - production-ready
  - vite
  - vitest
  - infrastructure
  - performance
  - frontend
  - fullstack
  - web-app
  - starter
  - boilerplate
  - cache
  - monitoring
  - logging
  - security
  - api-client
  - testing
  - quality
  - documentation
  - best-practices
  - modern
  - scalable

# GitHub Pages (for documentation)
pages:
  source:
    branch: main
    path: /docs
  build_type: legacy

# Social Preview
social_preview:
  image: 'docs/assets/social-preview.png'
  description: 'Enterprise-grade SvelteKit template with comprehensive infrastructure'

# License
license_template: mit

# Gitignore Template
gitignore_template: node

# Repository Metadata
homepage: 'https://kinderlystv-png.github.io/project-template'
