version: '3.8'

services:
  app:
    build:
      context: .
      target: development
      dockerfile: Dockerfile
    container_name: shinomontagka-dev
    volumes:
      - ./src:/app/src:cached
      - ./static:/app/static:cached
      - ./tests:/app/tests:cached
      - node_modules:/app/node_modules
    ports:
      - '3000:3000'
      - '24678:24678' # HMR port
    environment:
      - NODE_ENV=development
      - VITE_HOST=0.0.0.0
    env_file:
      - .env.development
    restart: unless-stopped
    healthcheck:
      test: ['CMD', 'wget', '--no-verbose', '--tries=1', '--spider', 'http://localhost:3000/health']
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s
    networks:
      - shinomontagka-network

volumes:
  node_modules:

networks:
  shinomontagka-network:
    driver: bridge
